<WSO2TELCO_DEP_DB>.ALTER TABLE sp_quota_limit
	ADD COLUMN createdby VARCHAR(255) DEFAULT NULL,
	ADD COLUMN createddate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	ADD COLUMN updatedby VARCHAR(255) DEFAULT NULL,
	ADD COLUMN updateddate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

